/* eslint-disable */

import { FunctionComponent } from 'react';
// Don't forget to install package: @types/react-native
import { ViewProps } from 'react-native';
import { GProps } from 'react-native-svg';

export { default as Icon1 } from './Icon1';
export { default as Icon2 } from './Icon2';
export { default as Icon20220630青氪 } from './Icon20220630青氪';
export { default as Icon3 } from './Icon3';
export { default as Icon4 } from './Icon4';
export { default as Icon5 } from './Icon5';
export { default as Icon6 } from './Icon6';
export { default as Icon7 } from './Icon7';
export { default as Icon8 } from './Icon8';
export { default as Icon9 } from './Icon9';
export { default as IconBeijin } from './IconBeijin';
export { default as IconBianjidizhi } from './IconBianjidizhi';
export { default as IconBofang } from './IconBofang';
export { default as IconBofang1 } from './IconBofang1';
export { default as IconCehui } from './IconCehui';
export { default as IconChengong } from './IconChengong';
export { default as IconDainzanDianji } from './IconDainzanDianji';
export { default as IconDianjiyangshi } from './IconDianjiyangshi';
export { default as IconDianpuFeilei } from './IconDianpuFeilei';
export { default as IconDianpuSousuo } from './IconDianpuSousuo';
export { default as IconDianpu } from './IconDianpu';
export { default as IconDianpumianxing } from './IconDianpumianxing';
export { default as IconDianzanWeidianji } from './IconDianzanWeidianji';
export { default as IconDianzanWeidianji1 } from './IconDianzanWeidianji1';
export { default as IconDianzanWeixuanzhong } from './IconDianzanWeixuanzhong';
export { default as IconDianzanXuanzhong } from './IconDianzanXuanzhong';
export { default as IconDingwei } from './IconDingwei';
export { default as IconDitu } from './IconDitu';
export { default as IconDitu1 } from './IconDitu1';
export { default as IconDizhiguangli } from './IconDizhiguangli';
export { default as IconFanghui } from './IconFanghui';
export { default as IconFanghuijiantou } from './IconFanghuijiantou';
export { default as IconFanghuijiantou1 } from './IconFanghuijiantou1';
export { default as IconFanhui } from './IconFanhui';
export { default as IconFanhuianniuZuo } from './IconFanhuianniuZuo';
export { default as IconFanhuianniu } from './IconFanhuianniu';
export { default as IconFanhuianniu1 } from './IconFanhuianniu1';
export { default as IconFankuizhongxin } from './IconFankuizhongxin';
export { default as IconFenxiang } from './IconFenxiang';
export { default as IconFenxiang1 } from './IconFenxiang1';
export { default as IconFuzhi } from './IconFuzhi';
export { default as IconGengduo } from './IconGengduo';
export { default as IconGengduo1 } from './IconGengduo1';
export { default as IconGengduohaoyou } from './IconGengduohaoyou';
export { default as IconGouduo } from './IconGouduo';
export { default as IconGouwucheMianxing } from './IconGouwucheMianxing';
export { default as IconGouwuche } from './IconGouwuche';
export { default as IconGuanbiBaise } from './IconGuanbiBaise';
export { default as IconGuanbiHeidi } from './IconGuanbiHeidi';
export { default as IconGuanbi } from './IconGuanbi';
export { default as IconGuangbiHeidi } from './IconGuangbiHeidi';
export { default as IconGuangbi } from './IconGuangbi';
export { default as IconHuati } from './IconHuati';
export { default as IconHuiyuanbiaoqian } from './IconHuiyuanbiaoqian';
export { default as IconHuiyuanbiaoqianbaisedianzui } from './IconHuiyuanbiaoqianbaisedianzui';
export { default as IconHuiyuanbiaoshi } from './IconHuiyuanbiaoshi';
export { default as IconHuiyuanbiaoshi1 } from './IconHuiyuanbiaoshi1';
export { default as IconHuiyuanzhongxing } from './IconHuiyuanzhongxing';
export { default as IconJia } from './IconJia';
export { default as IconJia1 } from './IconJia1';
export { default as IconJian } from './IconJian';
export { default as IconJian1 } from './IconJian1';
export { default as IconJiangouShang } from './IconJiangouShang';
export { default as IconJiangtouXia } from './IconJiangtouXia';
export { default as IconJiantouxiangshang } from './IconJiantouxiangshang';
export { default as IconJiazai } from './IconJiazai';
export { default as IconJinshi } from './IconJinshi';
export { default as IconJubao } from './IconJubao';
export { default as IconKaidian } from './IconKaidian';
export { default as IconKaiguangWeixuanzhong } from './IconKaiguangWeixuanzhong';
export { default as IconKaiguanXuanzhong } from './IconKaiguanXuanzhong';
export { default as IconKefuliaotian } from './IconKefuliaotian';
export { default as IconLianjie } from './IconLianjie';
export { default as IconLiaotian } from './IconLiaotian';
export { default as IconLiaotian1 } from './IconLiaotian1';
export { default as IconLijigoumai } from './IconLijigoumai';
export { default as IconPaishe } from './IconPaishe';
export { default as IconPaisheanniu } from './IconPaisheanniu';
export { default as IconPeisongjiantou } from './IconPeisongjiantou';
export { default as IconPinglun } from './IconPinglun';
export { default as IconPinglun1 } from './IconPinglun1';
export { default as IconQq } from './IconQq';
export { default as IconQuanshengyue } from './IconQuanshengyue';
export { default as IconQueshengtu } from './IconQueshengtu';
export { default as IconQueshengye } from './IconQueshengye';
export { default as IconQueshengye1 } from './IconQueshengye1';
export { default as IconRe } from './IconRe';
export { default as IconSaixuanjiantou } from './IconSaixuanjiantou';
export { default as IconSaixuanjiantou1 } from './IconSaixuanjiantou1';
export { default as IconSaixuanWeixuanzhongW } from './IconSaixuanWeixuanzhongW';
export { default as IconShaixuan } from './IconShaixuan';
export { default as IconShipingzanting } from './IconShipingzanting';
export { default as IconShoucangDianji } from './IconShoucangDianji';
export { default as IconShoucangWeidianji } from './IconShoucangWeidianji';
export { default as IconSonghuoshangmen } from './IconSonghuoshangmen';
export { default as IconSousuo } from './IconSousuo';
export { default as IconSousuo1 } from './IconSousuo1';
export { default as IconSousuo11 } from './IconSousuo11';
export { default as IconSousuo111 } from './IconSousuo111';
export { default as IconSousuo1111 } from './IconSousuo1111';
export { default as IconTabGuangzhu } from './IconTabGuangzhu';
export { default as IconTabTuijian } from './IconTabTuijian';
export { default as IconTabXiaoyuan } from './IconTabXiaoyuan';
export { default as IconTabZuixing } from './IconTabZuixing';
export { default as IconTanchuangGuanbi } from './IconTanchuangGuanbi';
export { default as IconTianji } from './IconTianji';
export { default as IconTianji1 } from './IconTianji1';
export { default as IconTianjiaLiaotianchuangkou } from './IconTianjiaLiaotianchuangkou';
export { default as IconTianjia } from './IconTianjia';
export { default as IconTousu } from './IconTousu';
export { default as IconWeixing } from './IconWeixing';
export { default as IconWeixuangzhong } from './IconWeixuangzhong';
export { default as IconWeixuanzhong } from './IconWeixuanzhong';
export { default as IconWeixuanzhong1 } from './IconWeixuanzhong1';
export { default as IconXaindanfanxiang } from './IconXaindanfanxiang';
export { default as IconXiangxiajiantouBaise } from './IconXiangxiajiantouBaise';
export { default as IconXiangxiajiantou } from './IconXiangxiajiantou';
export { default as IconXinghao } from './IconXinghao';
export { default as IconXuanze } from './IconXuanze';
export { default as IconXuanzhongHeise } from './IconXuanzhongHeise';
export { default as IconXuanzhong } from './IconXuanzhong';
export { default as IconXuanzhong1 } from './IconXuanzhong1';
export { default as IconXuanzhongzhuangtai } from './IconXuanzhongzhuangtai';
export { default as IconXuanzhuang } from './IconXuanzhuang';
export { default as IconYouhuijuanBeijingtu } from './IconYouhuijuanBeijingtu';
export { default as IconYouhuiquanWeixuanzhong } from './IconYouhuiquanWeixuanzhong';
export { default as IconYouhuiquanXuanzhong } from './IconYouhuiquanXuanzhong';
export { default as IconYouhuiquan } from './IconYouhuiquan';
export { default as IconZhaopianWeidianji } from './IconZhaopianWeidianji';
export { default as IconZhaopian } from './IconZhaopian';
export { default as IconZhaopianxuhao1 } from './IconZhaopianxuhao1';
export { default as IconZhaopianxuhao2 } from './IconZhaopianxuhao2';
export { default as IconZhaopianxuhao3 } from './IconZhaopianxuhao3';
export { default as IconZhaopianxuhao4 } from './IconZhaopianxuhao4';
export { default as IconZhaopianxuhao6 } from './IconZhaopianxuhao6';
export { default as IconZhaopianxuhao7 } from './IconZhaopianxuhao7';
export { default as IconZhaopianxuhao8 } from './IconZhaopianxuhao8';
export { default as IconZhaopianxuhao9 } from './IconZhaopianxuhao9';
export { default as Icon商品橱窗 } from './Icon商品橱窗';

interface Props extends GProps, ViewProps {
  name: '1' | '2' | '20220630青氪' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | 'beijin' | 'bianjidizhi' | 'bofang' | 'bofang(1)' | 'cehui' | 'chengong' | 'dainzan-dianji' | 'dianjiyangshi' | 'dianpu-feilei' | 'dianpu-sousuo' | 'dianpu' | 'dianpumianxing' | 'dianzan-weidianji' | 'dianzan-weidianji(1)' | 'dianzan-weixuanzhong' | 'dianzan-xuanzhong' | 'dingwei' | 'ditu' | 'ditu(1)' | 'dizhiguangli' | 'fanghui' | 'fanghuijiantou' | 'fanghuijiantou(1)' | 'fanhui' | 'fanhuianniu-zuo' | 'fanhuianniu' | 'fanhuianniu(1)' | 'fankuizhongxin' | 'fenxiang' | 'fenxiang(1)' | 'fuzhi' | 'gengduo' | 'gengduo(1)' | 'gengduohaoyou' | 'gouduo' | 'gouwuche-mianxing' | 'gouwuche' | 'guanbi-baise' | 'guanbi-heidi' | 'guanbi' | 'guangbi-heidi' | 'guangbi' | 'huati' | 'huiyuanbiaoqian' | 'huiyuanbiaoqianbaisedianzui' | 'huiyuanbiaoshi' | 'huiyuanbiaoshi(1)' | 'huiyuanzhongxing' | 'jia' | 'jia(1)' | 'jian' | 'jian(1)' | 'jiangou-shang' | 'jiangtou-xia' | 'jiantouxiangshang' | 'jiazai' | 'jinshi' | 'jubao' | 'kaidian' | 'kaiguangWeixuanzhong' | 'kaiguanXuanzhong' | 'kefuliaotian' | 'lianjie' | 'liaotian' | 'liaotian(1)' | 'lijigoumai' | 'paishe' | 'paisheanniu' | 'peisongjiantou' | 'pinglun' | 'pinglun(1)' | 'QQ' | 'quanshengyue' | 'queshengtu' | 'queshengye' | 'queshengye(1)' | 're' | 'saixuanjiantou' | 'saixuanjiantou(1)' | 'saixuanWeixuanzhongW' | 'shaixuan' | 'shipingzanting' | 'shoucang-dianji' | 'shoucang-weidianji' | 'songhuoshangmen' | 'sousuo' | 'sousuo(1)' | 'sousuo(1)(1)' | 'sousuo(1)(1)(1)' | 'sousuo(1)(1)(1)(1)' | 'tab-guangzhu' | 'tab-tuijian' | 'tab-xiaoyuan' | 'tab-zuixing' | 'tanchuangGuanbi' | 'tianji' | 'tianji(1)' | 'tianjia-liaotianchuangkou' | 'tianjia' | 'tousu' | 'weixing' | 'weixuangzhong' | 'weixuanzhong' | 'weixuanzhong(1)' | 'xaindanfanxiang' | 'xiangxiajiantou-baise' | 'xiangxiajiantou' | 'xinghao' | 'xuanze' | 'xuanzhong-heise' | 'xuanzhong' | 'xuanzhong(1)' | 'xuanzhongzhuangtai' | 'xuanzhuang' | 'youhuijuan-beijingtu' | 'youhuiquan-weixuanzhong' | 'youhuiquan-xuanzhong' | 'youhuiquan' | 'zhaopian-weidianji' | 'zhaopian' | 'zhaopianxuhao-1' | 'zhaopianxuhao-2' | 'zhaopianxuhao-3' | 'zhaopianxuhao-4' | 'zhaopianxuhao-6' | 'zhaopianxuhao-7' | 'zhaopianxuhao-8' | 'zhaopianxuhao-9' | '商品橱窗';
  size?: number;
  color?: string | string[];
}

declare const IconFont: FunctionComponent<Props>;

export default IconFont;
